name: Build Vue
on:
  push: master
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.0
        with:
          username: "mizuka-wu"
          reponame: "hilichurls-language"
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
